export interface MaterialData {
  slug: string;
  name: string;
  overview: string;
  federalLaw: string;
  acceptedMaterials: string[];
  nationalTakeBackPrograms: string;
}

export const materialsData: Record<string, MaterialData> = {
  electronics: {
    slug: "electronics",
    name: "Electronics",
    overview: "Electronics (e-waste) contain toxic heavy metals like lead, mercury, and cadmium, but also valuable resources like gold and copper. Proper disposal ensures these materials are safely extracted rather than leaching into groundwater from landfills.",
    federalLaw: "Currently, there is no comprehensive federal law in the United States mandating the recycling of electronic waste. The Resource Conservation and Recovery Act (RCRA) does regulate the disposal of toxic waste, which covers some commercial e-waste, but household e-waste is largely exempt from federal regulation. As a result, e-waste management is governed by a patchwork of state laws. Currently, 25 states and the District of Columbia have enacted legislation establishing statewide e-waste recycling programs, many of which use an Extended Producer Responsibility (EPR) model where manufacturers must fund recycling efforts.",
    acceptedMaterials: [
      "Televisions (CRT, LCD, Plasma)",
      "Computers (Desktops, Laptops, Tablets)",
      "Monitors and displays",
      "Keyboards, mice, and peripherals",
      "Printers, scanners, and fax machines",
      "VCRs, DVD players, and gaming consoles",
      "Cell phones and smart devices"
    ],
    nationalTakeBackPrograms: "Several major retailers and manufacturers offer national take-back programs. Best Buy allows customers to drop off up to three electronics per day per household at most stores, regardless of where they were purchased. Staples and Office Depot offer similar recycling services for office technology. Additionally, Apple, Dell, and HP have mail-in programs or in-store drop-offs for their branded products. Network carriers like AT&T, Verizon, and T-Mobile frequently accept old phones for recycling or trade-in credit."
  },
  "paint-solvents": {
    slug: "paint-solvents",
    name: "Paint & Solvents",
    overview: "Paint products and solvents are highly flammable and can contain volatile organic compounds (VOCs). If disposed of improperly, they can contaminate soil and water systems.",
    federalLaw: "Under the federal Resource Conservation and Recovery Act (RCRA), oil-based paints and highly flammable solvents are classified as hazardous waste when generated by businesses and must be disposed of at permitted hazardous waste facilities. Household hazardous waste (HHW), including residential paint, is exempt from federal RCRA requirements. However, the EPA strongly encourages proper management through local HHW programs. Furthermore, the federal government has supported initiatives like PaintCare, an industry-led non-profit program establishing paint stewardship laws state-by-state, currently active in 11 states and D.C.",
    acceptedMaterials: [
      "Latex (water-based) paint",
      "Oil-based paint and alkyd paint",
      "Stains, varnishes, and lacquers",
      "Polyurethane and clear coatings",
      "Paint thinners and mineral spirits",
      "Rust preventatives and sealers"
    ],
    nationalTakeBackPrograms: "The most prominent national program is PaintCare, which operates in states with active paint stewardship laws. PaintCare sets up drop-off locations at hardware stores, paint retail stores, and solid waste facilities. Residents can drop off leftover architectural paint for free. If you are not in a PaintCare state, big-box retailers like Lowe's or The Home Depot occasionally host take-back events, but daily drop-offs are typically handled by municipal Household Hazardous Waste (HHW) facilities."
  },
  mattresses: {
    slug: "mattresses",
    name: "Mattresses",
    overview: "Mattresses are notoriously difficult for landfills to manage due to their bulk and inability to compress. However, up to 90% of a mattress can be recycled, including steel springs, foam, and wood.",
    federalLaw: "There are no federal laws dictating mattress recycling or disposal in the United States. Due to their size, mattresses quickly fill up municipal landfills and pose risks of catching in landfill equipment, creating 'fluff' that poses fire hazards. As a result, the Mattress Recycling Council (MRC) was formed by the industry to implement state-mandated Extended Producer Responsibility (EPR) programs. These programs are currently mandated by state laws in California, Connecticut, Rhode Island, and Oregon, requiring a recycling fee at the time of purchase to fund statewide collection.",
    acceptedMaterials: [
      "Innerspring mattresses",
      "Memory foam mattresses",
      "Latex and hybrid mattresses",
      "Box springs and foundations",
      "Futon mattresses (must detach from frame)"
    ],
    nationalTakeBackPrograms: "The Mattress Recycling Council operates the 'Bye Bye Mattress' program, providing thousands of drop-off locations and collection events in participating states. Nationally, many retailers like Mattress Firm offer haul-away and recycling services for a fee when delivering a new mattress. Charities such as the Salvation Army or Habitat for Humanity ReStore may accept gently used mattresses free of rips, stains, or bed bugs, though acceptance policies vary heavily by local branch."
  },
  tires: {
    slug: "tires",
    name: "Tires",
    overview: "Scrap tires pose significant environmental and health risks if stockpiled, acting as breeding grounds for mosquitoes and posing severe fire hazards that release toxic smoke.",
    federalLaw: "The federal government generally delegates scrap tire management to individual states. The Resource Conservation and Recovery Act (RCRA) does not classify scrap tires as hazardous waste. However, due to the severe environmental impact of tire fires, nearly all 50 states have enacted dedicated scrap tire laws or regulations. Most states ban whole tires from landfills and require a disposal fee at the point of purchase to fund state-run cleanups and recycling programs. These programs process tires into tire-derived fuel, rubberized asphalt, and mulch.",
    acceptedMaterials: [
      "Passenger car and light truck tires",
      "Motorcycle and ATV tires",
      "Commercial truck tires",
      "Agricultural and tractor tires",
      "Bicycle tires and inner tubes"
    ],
    nationalTakeBackPrograms: "There are few free 'take-back' programs for tires, as disposal almost always incurs a processing fee. National auto centers and tire retailers, such as Discount Tire, Firestone, and Walmart Auto Care Centers, will accept old tires for recycling when you purchase new ones, charging a mandatory state fee (usually $1 to $5 per tire). If you are looking to dispose of tires without a purchase, these same retailers or your local municipal solid waste facility will typically accept them for a small drop-off fee."
  },
  batteries: {
    slug: "batteries",
    name: "Batteries",
    overview: "Batteries range from benign alkaline cells to highly volatile lithium-ion packs. Improper disposal of rechargeable batteries is the leading cause of fires in waste management facilities.",
    federalLaw: "The Mercury-Containing and Rechargeable Battery Management Act of 1996 is the primary federal law governing batteries. It phases out the use of mercury in batteries and mandates that rechargeable batteries (like Ni-Cd and lead-acid) must be easily removable from products and labeled for recycling. This act facilitated the creation of national, industry-funded collection programs. Lead-acid car batteries are governed under RCRA and have incredibly high recycling rates (over 99%) due to core charge laws in most states.",
    acceptedMaterials: [
      "Alkaline batteries (AA, AAA, C, D)",
      "Lithium-ion (Li-ion) batteries",
      "Nickel-cadmium (Ni-Cd) batteries",
      "Nickel-metal hydride (Ni-MH) batteries",
      "Button cell batteries (watch/hearing aid)",
      "Lead-acid (automotive) batteries"
    ],
    nationalTakeBackPrograms: "Call2Recycle is the premier national program for rechargeable battery recycling, offering tens of thousands of drop-off bins at retailers like The Home Depot, Lowe's, and Staples. These locations accept rechargeable batteries (Li-ion, Ni-Cd) and cell phones for free. For automotive batteries, retailers like AutoZone, Advance Auto Parts, and O'Reilly Auto Parts accept core returns and old batteries for free, often providing a store credit or gift card as an incentive."
  },
  "motor-oil": {
    slug: "motor-oil",
    name: "Motor Oil",
    overview: "Used motor oil is highly toxic to the environment. A single gallon of improperly disposed motor oil can contaminate one million gallons of fresh water.",
    federalLaw: "Under the EPA's Used Oil Management Standards (part of RCRA), used oil is presumed to be recycled and thus is largely exempt from hazardous waste regulations if managed properly. Federal law requires proper labeling ('Used Oil'), secure storage, and response to any spills. If used oil is mixed with a hazardous solvent, it may suddenly become regulated as a hazardous waste. The EPA strongly enforces against the dumping of used oil into sewers, drainage systems, or the ground.",
    acceptedMaterials: [
      "Used motor oil",
      "Transmission fluid",
      "Hydraulic fluid",
      "Power steering fluid",
      "Gear oil",
      "Used oil filters"
    ],
    nationalTakeBackPrograms: "The automotive industry offers widespread national take-back programs. Major retailers like AutoZone, Advance Auto Parts, O'Reilly Auto Parts, and Walmart Tire & Lube Express generally accept used motor oil for free (typically capped at 5 gallons per visit per person). Ensure the oil is stored in a clean, leak-proof container and is not mixed with antifreeze, water, or other solvents, as contaminated oil will be rejected by these locations."
  },
  "light-bulbs": {
    slug: "light-bulbs",
    name: "Light Bulbs",
    overview: "While incandescent and LED bulbs are generally safe, fluorescent tubes and CFLs contain small amounts of mercury, making them hazardous if broken.",
    federalLaw: "The EPA regulates fluorescent bulbs under the Universal Waste Rule, a subset of RCRA designed to encourage the recycling of widely generated hazardous items. Businesses are generally required to recycle mercury-containing lamps, while households are often exempt. However, the EPA strongly advises against throwing CFLs and fluorescent tubes in regular trash to prevent mercury contamination. The Energy Independence and Security Act of 2007 also phased out inefficient incandescent bulbs, driving the shift toward LEDs and CFLs.",
    acceptedMaterials: [
      "Compact Fluorescent Lamps (CFLs)",
      "Fluorescent tubes (T4, T5, T8, T12)",
      "High-Intensity Discharge (HID) lamps",
      "Neon and argon lamps",
      "LED bulbs",
      "Halogen and incandescent bulbs"
    ],
    nationalTakeBackPrograms: "For residential CFLs, major retailers like Lowe's and The Home Depot offer free drop-off recycling bins near the store entrance. However, these bins typically do not accept long fluorescent tubes due to breakage risks. For fluorescent tubes and large volumes of commercial lamps, specialized mail-back programs (like those sold by Waste Management or Grainger) provide pre-paid shipping boxes. Local HHW events remain the best option for residential fluorescent tube disposal."
  },
  "prescription-drugs": {
    slug: "prescription-drugs",
    name: "Prescription Drugs",
    overview: "Improper disposal of medications leads to accidental poisonings, prescription drug abuse, and water contamination. Flushing drugs is highly discouraged.",
    federalLaw: "The Secure and Responsible Drug Disposal Act of 2010 amended the Controlled Substances Act, allowing the DEA to develop regulations for the public to safely dispose of unused or expired controlled substances. This authorized pharmacies, hospitals, and law enforcement agencies to maintain secure collection receptacles. The EPA also finalized the Management Standards for Hazardous Waste Pharmaceuticals in 2019, explicitly banning healthcare facilities from flushing hazardous waste pharmaceuticals down the drain.",
    acceptedMaterials: [
      "Prescription medications (pills, liquids)",
      "Over-the-counter medications",
      "Vitamins and supplements",
      "Pet medications",
      "Medicated ointments and lotions",
      "Inhalers (requires special handling)"
    ],
    nationalTakeBackPrograms: "The DEA hosts 'National Prescription Drug Take Back Day' biannually (typically April and October) at thousands of locations nationwide. Year-round, major retail pharmacy chains like Walgreens and CVS have installed secure drop-boxes in thousands of their locations. You can anonymously drop off solid medications; liquid medications must be kept in sealed containers. Sharps (needles) and illicit drugs are strictly prohibited in these bins."
  },
  chemicals: {
    slug: "chemicals",
    name: "Household Chemicals",
    overview: "Cleaning agents, pesticides, and pool chemicals can react dangerously if mixed and pose severe toxicity risks to sanitation workers and the environment.",
    federalLaw: "Household hazardous waste (HHW) is excluded from federal hazardous waste regulations under the Resource Conservation and Recovery Act (RCRA). This means individuals are not legally penalized by the EPA for throwing household chemicals in the trash. However, the EPA strictly regulates the commercial production, transport, and disposal of these chemicals. The Federal Insecticide, Fungicide, and Rodenticide Act (FIFRA) also strictly dictates how pesticides must be labeled, including specific disposal instructions that users are legally obligated to follow.",
    acceptedMaterials: [
      "Bleach and ammonia products",
      "Pesticides, herbicides, and fertilizers",
      "Pool chemicals (chlorine, algaecides)",
      "Drain cleaners and oven cleaners",
      "Aerosol sprays (if not entirely empty)",
      "Photographic chemicals"
    ],
    nationalTakeBackPrograms: "Due to the extreme volatility and liability of chemical waste, there are virtually no retail-based national take-back programs for household chemicals. Disposal must be handled through municipal Household Hazardous Waste (HHW) facilities or recurring county collection events. These facilities employ trained chemists who can properly segregate incompatible chemicals (like keeping bleach away from ammonia to prevent toxic gas) and package them for safe incineration or neutralization."
  },
  appliances: {
    slug: "appliances",
    name: "Large Appliances",
    overview: "White goods like refrigerators and AC units contain refrigerants (Freon) and oils that must be properly recovered before the massive steel chassis can be shredded and recycled.",
    federalLaw: "The Clean Air Act directly impacts appliance disposal. Section 608 prohibits the intentional venting of refrigerants (like CFCs, HCFCs, and HFCs) into the atmosphere during the disposal of refrigeration and air-conditioning equipment. Federal law requires that only certified technicians use EPA-approved recovery equipment to evacuate refrigerants from an appliance before it is crushed or dismantled. The EPA also enforces the Safe Disposal Requirements, mandating the removal of PCBs (often found in older capacitors) and mercury switches.",
    acceptedMaterials: [
      "Refrigerators and freezers",
      "Air conditioners (window and portable)",
      "Washers and dryers",
      "Dishwashers",
      "Ovens, stoves, and ranges",
      "Water heaters and furnaces"
    ],
    nationalTakeBackPrograms: "Appliance disposal is heavily supported by utility companies through the EPA's Responsible Appliance Disposal (RAD) program. Many local energy providers offer free pickup and a cash rebate (e.g., $50) for turning in old, inefficient working refrigerators. Nationally, major retailers like Best Buy, The Home Depot, and Lowe's offer haul-away services for a nominal fee when delivering a new appliance. Local scrap metal yards will often accept non-refrigerant appliances for free or pay you scrap value."
  },
  "medical-sharps": {
    slug: "medical-sharps",
    name: "Medical Sharps",
    overview: "Needles, syringes, and lancets pose a severe transmission risk for bloodborne pathogens to sanitation workers if thrown loosely into the trash or recycling.",
    federalLaw: "At the federal level, the Occupational Safety and Health Administration (OSHA) Bloodborne Pathogens standard heavily regulates sharps management for healthcare workers and employers. However, home-generated sharps are not federally regulated as medical waste. The EPA provides strong guidance advocating for containment in FDA-cleared sharps containers, but ultimately leaves enforcement to the states. Several states, including California and Massachusetts, have strictly banned household sharps from being disposed of in the municipal trash.",
    acceptedMaterials: [
      "Needles and syringes",
      "Lancets (fingerstick devices)",
      "Auto-injectors (EpiPens, insulin pens)",
      "Infusion sets",
      "Connection needles",
      "Scalpels and razor blades"
    ],
    nationalTakeBackPrograms: "Retail pharmacies generally do not accept sharps in their drug drop-boxes due to puncture risks. The safest national option is the use of FDA-cleared mail-back programs. Companies like Sharps Compliance or Stericycle sell complete kits that include a biohazard container and a pre-paid return shipping box approved by the USPS. Some local health departments or police stations maintain secure sharps kiosks. Alternatively, many states allow sharps to be sealed in heavy-duty plastic bottles (like laundry detergent jugs) and labeled 'DO NOT RECYCLE' before trashing, though this is heavily location-dependent."
  },
  "fire-extinguishers": {
    slug: "fire-extinguishers",
    name: "Fire Extinguishers",
    overview: "Fire extinguishers are pressurized vessels containing dry chemicals, foams, or gases. If compacted in a garbage truck, they can explode violently.",
    federalLaw: "Fire extinguishers are regulated under OSHA and the DOT regarding their manufacturing, testing, and transport. As waste, business-generated fire extinguishers might be considered hazardous under RCRA if they contain toxic chemicals (like Halon, an ozone-depleting substance banned from new production). For households, they are generally not classified as hazardous waste federally, but the high-pressure cylinder presents a physical hazard that bans them from standard municipal solid waste systems.",
    acceptedMaterials: [
      "ABC Dry Chemical extinguishers",
      "Carbon Dioxide (CO2) extinguishers",
      "Water and Foam extinguishers",
      "Halon extinguishers (vintage/specialty)",
      "Purple K (dry chemical)",
      "Empty depressurized cylinders"
    ],
    nationalTakeBackPrograms: "There is no single national retailer that takes back fire extinguishers. Your best option is to contact local fire equipment dealers or fire protection companies; they frequently accept old extinguishers to bleed off pressure and recycle the steel/aluminum cylinders. Some local fire departments will accept them, but policies vary widely. If the gauge reads completely empty (zero pressure), some scrap metal yards will accept the cylinder if the valve head is completely removed."
  },
  "propane-tanks": {
    slug: "propane-tanks",
    name: "Propane Tanks",
    overview: "Even seemingly empty propane cylinders contain residual explosive gas. They are the leading cause of explosions in recycling centers and garbage trucks.",
    federalLaw: "The Department of Transportation (DOT) strictly regulates the manufacture and transport of pressurized cylinders, requiring periodic requalification testing (usually every 12 years for 20lb tanks). The EPA regulates large-scale venting of propane under the Clean Air Act, though it is not an ozone-depleting substance. Household propane tanks are universally banned from municipal trash and curbside recycling bins due to their severe explosive hazard when crushed.",
    acceptedMaterials: [
      "1-pound camping propane cylinders",
      "20-pound BBQ grill tanks",
      "MAPP gas cylinders",
      "Butane canisters",
      "Helium balloon tanks",
      "Freon recovery cylinders"
    ],
    nationalTakeBackPrograms: "For standard 20lb BBQ tanks, the easiest disposal method is utilizing a national tank exchange program like Blue Rhino or AmeriGas. You can leave an old, out-of-date tank beside the exchange cage at retailers like Walmart, The Home Depot, or convenience stores. The companies will retrieve it for refurbishment or safe recycling. For the small 1lb green camping cylinders, disposal is much harder; they must typically go to a municipal Household Hazardous Waste facility, though some national parks run localized collection programs."
  },
  furniture: {
    slug: "furniture",
    name: "Furniture",
    overview: "Bulky furniture consumes massive landfill volume. While wood and metal can be recycled, treated fabrics, foams, and composite woods make whole-piece recycling difficult.",
    federalLaw: "There are no federal laws mandating the recycling or specific disposal methods for household furniture. The EPA classifies furniture as Municipal Solid Waste (MSW) or bulky waste. Federal regulations only come into play if the furniture contains hazardous materials, such as older items treated with lead paint or specific toxic flame retardants (like PBDEs), though these are generally regulated at the manufacturing level rather than the consumer disposal level. Most disposal policies are enacted by local municipalities regarding curbside pickup limits.",
    acceptedMaterials: [
      "Couches and sofas",
      "Chairs and recliners",
      "Tables and desks",
      "Dressers and cabinets",
      "Bed frames and headboards",
      "Patio furniture"
    ],
    nationalTakeBackPrograms: "Furniture disposal relies heavily on local charities and bulky waste pickups rather than retail take-back programs. National charities like Habitat for Humanity ReStore, Goodwill, and the Salvation Army will often pick up gently used furniture directly from your home for free, providing a tax-deductible receipt. If the furniture is heavily damaged, stained, or torn, it will be rejected by charities. In those cases, you must utilize your city's 311 bulky item pickup service or hire a junk removal company."
  },
  clothing: {
    slug: "clothing",
    name: "Clothing & Textiles",
    overview: "Textiles are one of the fastest-growing waste streams. Synthetic fibers (polyester, nylon) take hundreds of years to decompose and shed microplastics.",
    federalLaw: "The EPA tracks textile waste generation but has no federal mandates for textile recycling. In recent years, as fast fashion has accelerated landfill accumulation, some states are pushing for Extended Producer Responsibility (EPR) bills for textiles, but none have passed federally. Currently, textile disposal is virtually unregulated, though the FTC heavily regulates how textiles are labeled (fiber content, origin) under the Textile Fiber Products Identification Act.",
    acceptedMaterials: [
      "Shirts, pants, and dresses",
      "Coats and jackets",
      "Shoes and boots",
      "Towels and bedding",
      "Curtains and drapes",
      "Belts, hats, and accessories"
    ],
    nationalTakeBackPrograms: "Many national apparel brands have implemented take-back programs. H&M and Zara offer recycling bins in their retail stores for any brand of clothing in any condition, often giving a discount voucher in return. Madewell offers a denim recycling program. Retold Recycling provides a mail-in bag service for a fee, accepting even torn or stained textiles which are then shredded for insulation or rags. Otherwise, charities like Goodwill or dedicated textile drop-boxes (like Planet Aid) are omnipresent nationwide."
  }
};
